name: 'Kris Bryant, MA, LPC'
favicon: null
layout_spectrum: 0.4824
typography_spectrum: 0.32096
title: 'Counseling & Life Coaching | Oklahoma City, OK'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141414'
    - '#939392'
    - '#4b4b4b'
    - '#bfbfbf'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.86267504026182
purpose: []
