name: 'Kris Bryant, MA, LPC'
favicon: null
layout_spectrum: 0.6631804762873799
typography_spectrum: 0.30956805194728076
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6844061643350869
  lightness: 0.17256536171771586
  saturation: 0.4097865526564419
  rhythmicContrast: 0.86267504026182
purpose: []
